config/routes.rb
Rails.application.routes.draw do

  # Fastly Rails Dashboard
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'

  # Application
  # @implemented
  root to: 'home#index'
  resources :films, only: [:index, :show]
  resources :projects, only: [:index, :show]
  resource  :contact, only: [:create]
  resource  :newsletter, only: [:create, :destroy]

  # User built-in dashboard
  # @implemented
  namespace :dashboard do
  	get '', to: 'home#index'
  end

  # Authentication
  # @implemtented
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # @implemented
  namespace :api, path: '/', constraint: { subdomain: 'api' } do
  	namespace :v1 do
  	 with_options only: [:index, :show] do |list|
  	 	list.resources :films
  	 	list.resources :projects
  	 	list.resources :videos
  	  end
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact 
	include ActiveModel::Conversion
	include ActiveModel::Validations

	attr_accessor :name, :phone, :email, :message
	
	def initialize(params: {})
		@name = params[:name]
		@phone = params[:phone]
		@email = params[:email]
		@message = params[:message]
	end

	def persisted?
	   false
	end

	validates :name,
			  presence: true,
			  unqueness: false,
			  allow_blank: true,
			  length: {minimum: 3, maximum: 30}
    
    validates :phone,
    		  presence: true,
    		  uniqueness: false,
    		  allow_blank: false,
    		  length: {minimum: 3, maximum:  15}

    validates :email,
    		  presence: true,
    		  uniqueness: false,
    		  allow_blank: false,
    		  length: {minimum: 3, maximum: 245}

    validates :message,
    		  presence: true,
    		  uniqueness: false,
    		  allow_blank: false,
    		  length: {minimum: 3, maximum: 1000}
end

app/models/film.rb
class Film < ApplicationRecord
  self.table_name = 'films'
  self.primary_key = 'id'

  validates :name,	
  			presence: true,
  			uniqueness: false,
  			allow_blank: false,
  			length: {minimum: 3, maximum: 30}

  validates :description,
  			presence: true,
  			uniqueness: false,
  			allow_blank: false,
  			length: {minimum: 3, maximum: 10_000}
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  self.table_name = 'videos'
  self.primary_key = 'id'

  validates :name,
  			presence: true,
  			uniqueness: false,
  			allow_blank: false,
  			length: {minimum: 3, maximum: 300}

  validates :description,
  			presence: true,
  			uniqueness: false,
  			allow_blank: false,
  			length: {minimum: 3, maximum: 400}

  validates :link,
  			presence: true,
  			uniqueness: false,
  			allow_blank: false,
  			length: {minimum: 3, maximum: 245}
end

app/controllers/api/v1/films_controller.rb
class API::V1::FilmsController < ApplicationController
  before_action :set_film, only: [:show]
  
  respond_to :json, :js
  def index
  	films = Film.all
  	render json: films, only: [:name, :description]
  end
  def show
  end

  private
   def set_film
     film = Film.find(params[:id])
     render json: film, only: [:name, :description]
   end
end

app/controllers/api/v1/projects_controller.rb
class API::V1::ProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  respond_to :json, :js
  def index
  	projects = Project.all
  	render json: projects, only: [:name, :description]
  end
  def show
  end

  private
   def set_project
     project = Project.find(params[:id])
     render json: project, only: [:name, :description]
   end
end

app/controllers/api/v1/videos_controller.rb
class API::V1::VideosController < ApplicationController
  before_action :set_video, only: [:name, :description, :link]
  respond_to :json, :js

  def index
  	videos = Video.all
  	render json: videos, only: [:name, :description, :link]
  end
  def show
  end

  private
   def set_video
     video = Video.find(params[:id])
     render json: video, only: [:name, :description, :link]
   end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@contact = Contact.new
  end
end

app/helpers/api/v1/videos_helper.rb
module API::V1::VideosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/home_helper.rb
module Dashboard::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/_form.html.erb
<%=  form_for(@contact, {url: contact_path, method: :post}) do |f| %>
 <div class='col-md-6'>
  <div class='field'>
   <div class='col-md-12'>
  	 <%= f.text_field :name, class: 'form-control', required: 'required',
  	 placeholder: 'Digite o nome', autocomplete:'off' %>
  </div>
 </div>
  <div class='field'>
  	<div class='col-md-12'>
      <%= f.text_field :phone, class: 'form-control', required: 'required',
  	  placeholder: 'Digite o telefone', autocomplete: 'off' %>
  	</div>
  </div>
  <div class='field'>
   <div class='col-md-12'>
     <%= f.email_field :email, class: 'form-control', required: 'required',
  	 placeholder: 'Digite o e-mail', autocomplete: 'off' %>
  </div>
</div>
</div>
<div class='col-md-6'>
  <div class='field'>
   <div class='col-md-12'>
  	<%= f.text_area :message, class: 'form-control', required: 'required',
  	placeholder: 'Deixe sua mensagem', autocomplete: 'off' %>
   </div>
  </div>
</div>
<div class='col-md-4 col-md-offset-4'>
  <div class='field'>
    <div class='col-md-12'>
  	<%= f.submit 'Enviar Mensagem', class: 'btn btn-primary btn-lg top' %>
  	</div>
  </div>
</div>
<% end %>

app/views/dashboard/home/index.html.erb
<h1>Dashboard::Home#index</h1>
<p>Find me in app/views/dashboard/home/index.html.erb</p>

app/views/home/index.html.erb
<%= render partial: 'layouts/header' %>

<% provide :title, 'Home' %>

<div id='home' class='jumbotron'>
 <div class='container'>
	 <div class='row'>
		  <div class='col-md-11 col-md-offset-1'>
        <ul class='list-unstyled'>
         <li><h4 class='text-left'>NÓS SOMOS A ALVOROÇO FILMES</h4></li>
         <li><h1 class='text-center'><strong>ALVOROÇO
         <i class='glyphicon glyphicon-search'></i> FILMES</strong></h1></li>
         <li><p class='text-right'> Lorem ipsum lorem siamet dolor.</p></li>
        </ul><!-- list-unstyled -->
		 </div><!--  col-md-12 -->
	  </div><!-- row -->
   </div><!-- container -->
</div><!-- presenter -->

<section id='about'>
  <div class='container'>
  	 <div class='row'>
  	 	<div class='col-md-12' ng-controller='TabController as tabCtrl'>

  	 		 <ul class='breadcrumb'>
  	 		 	<li><%= link_to 'Home', '' %></li>
  	 		 </ul><!-- list-unstyled -->

  	 		 <ul class='list-unstyled list-inline'>
  	 		 	 <li><a href="" ng-click="tabCtrl.setTab(1)">ALVOROÇO FILMES</a></li>
  	 		 	 <li><a href="" ng-click="tabCtrl.setTab(2)">EVANDRO BERLESI</a></li>
         </ul><!-- list-unstyled -->
         <hr>

  	 		<div class='row' ng-show="tabCtrl.getTab(1)">

        <ul class='list-unstyled text-center'>
            <li><h1><strong>SERVIÇOS</strong></h1></li>
            <li><p>Conheça todos os nossos serviços.</p></li>
            <li><br></li>
        </ul><!-- list-unstyled -->

         <div class='col-md-4 col-sm-4 col-xs-4'>
  	 		 	  <ul class='list-unstyled text-center padding'>
  	 		 	  	 <li><h1><%= fa_icon 'facebook' %></h1></li>
  	 		 	  	 <li><h3><strong>VT PUBLICITÁRIO</strong></h3></li>
               <li><p>Lorem ipsum lorem siamet dollor imet irlhem. lorem
               ipsum lorem dolor imet siamet ilrhm.</p></li>
  	 		 	  </ul><!-- list-unstyled -->
  	 		 </div><!-- col-md-6 -->

  	 		 <div class='col-md-4 col-sm-4 col-xs-4'>
  	 		 	  <ul class='list-unstyled text-center padding'>
  	 		 	     <li><h1><%= fa_icon 'twitter' %></h1></li>
  	 		 	  	 <li><h3><strong>VIDEO INSTITUCIONAL</strong></h3></li>
               <li><p>Lorem ipsum lorem siamet dollor imet irlhem. lorem
               ipsum lorem dolor imet siamet ilrhm.</p></li>
  	 		 	  </ul><!-- list-unstyled -->
  	 		 </div><!-- col-md-6 -->

  	 		 <div class='col-md-4 col-sm-4 col-xs-4'>
  	 		 	  <ul class='list-unstyled text-center padding'>
  	 		 	  	 <li><h1><%= fa_icon 'linkedin' %></h1></li>
  	 		 	  	 <li><h3><strong>PROJETOS CINEMA E TELEVISÃO</strong></h3></li>
               <li><p>Lorem ipsum lorem siamet dollor imet irlhem. lorem
               ipsum lorem dolor imet siamet ilrhm.</p></li>
  	 		 	  </ul><!-- list-unstyled -->
  	 		 </div><!-- col-md-6 -->

  	 		 <div class='col-md-4 col-sm-4 col-xs-4
          col-xs-offset-2 col-sm-offset-2 col-md-offset-2'>
  	 		 	  <ul class='list-unstyled text-center padding'>
  	 		 	  	 <li><h1><%= fa_icon 'vimeo' %></h1></li>
  	 		 	  	 <li><h3><strong>AUDIOVISUAL EM GERAL</strong></h3></li>
               <li><p>Lorem ipsum lorem siamet dollor imet irlhem. lorem
               ipsum lorem dolor imet siamet ilrhm.</p></li>
  	 		 	  </ul><!-- list-unstyled -->
  	 		 </div><!-- col-md-12 -->

  	 		 <div class='col-md-4 col-sm-4 col-xs-4'>
  	 		 	  <ul class='list-unstyled text-center padding'>
  	 		 	  	 <li><h1><%= fa_icon 'youtube' %></h1></li>
  	 		 	  	 <li><h3><strong>OFICINA PARA CINEMA, TELEVISÃO</strong></h3></li>
               <li><p>Lorem ipsum lorem siamet dollor imet irlhem. lorem
               ipsum lorem dolor imet siamet ilrhm.</p></li>
  	 		 	  </ul><!-- list-unstyled -->
  	 		 </div><!-- col-md-12 -->
  	 	 </div>

  	 	   <div class='row' ng-show='tabCtrl.getTab(2)'>
  	 	   	 <div class='col-md-12'>
  	 	   	 	 <h2><strong>EVANDRO BERLESI</strong></h2>
  	 	   	 	 <h5 class='badge'>Roteirista,Escritor e Diretor</h5>

  	 	   	 	 <p>Engressou no unviverso artistico em 1995 através do teatro,
  	 	   	 	  destacando-se como ator em diversas montagens cênicas. Descobriu
  	 	   	 	  sua habilidade de escrever ainda na infancia, quando criava pequenos
  	 	   	 	  roteiros de filmes sonhando um dia trabalhar com cinema.

  	 	   	 	  Em 2005, com o curta metragem o Japonês da Coréia (direção de Rodrigo
  	 	   	 	  Castelhano), seu 5 roteiro filmado, Evandro destacou-se na função de
  	 	   	 	  roteirista após acumular 10 prêmios em festivais nacionais, incluindo de
  	 	   	 	  melhor roteiro.

  	 	   	 	  Em 2006 foi o grande vencedor do Prêmio Revelação Literária da Feira do
  	 	   	    Livro de Porto Alegre.

  	 	   	    Em 2007, escreveu e lançou seu primeiro livro (independente) Eu odeio o
  	 	   	    Orkut, destacando-se nacionamente em programas como o programa do Jô (Rede Globo),
  	 	   	    charme (SBT), Pânico (Jovem Pan)...

  	 	   		  Em 2008 lançou seu primeiro longa metragem (roteiro e direção, que divide com
  	 	   	  	Castelhano), a comédia romântica Dá 1 Tempo! (filme que teve estreia na 13 Mostra
  	 	   	    de Cinema Tiradentes/MG) e seu segundo livro Arrependimento Mata (Besouro Box),
  	 	   	    recebendo da Prefeitura Municipal de Alvorada o titulo de honra ao mérito pelo
  	 	   	    trabalho realizado. Evandro também escreveu roteiros para televisão: seriado
  	 	   	    vidAnormal (TvCom/RBS) e duas micro-séries para o SBT, Verão o Amor e perfume de
  	 	   	    de Hortênsia (direção de Ivo Schergi Jr.). em 2009 inaugurou a produtora Alvoroço
  	 	   	    Filmes realizando o projeto Alvoroço nas Escolas, onde diversos alunos da rede publica
  	 	   	    da cidade aprenderam a fazer cinema na prática, realizando 4 curtas: Preserve-se,
  	 	   	    Tecnicamente Apavorados, Achei um violão e Tem gente! (selecionados para 4 festivais
  	 	   	    de cinema em 2010)

  	 	   	    Em maio de 2010 realizou um longe metragem em apenas 3 dias. Video Suícida é uma
  	 	   	    experiencia cinematográfica totalmente independente e solitária. O filme foi escrito
  	 	   	    , dirigido, produzido e editado por Evandro.

  	 	   	    Em 2011 lançou o longa Eu odeio o Orkut, adaptação do seu livro, com Jairo Mattos,
  	 	   	    Julio Rocha e Luana Piovani no elenco (distribuição Amazon).

  	 	   	    Devido ao sucesso da primeira edição do projeto. 2012 foi o ano do Alvoroço nas
  	 	   	    Escolas 2, desta vez concluido com 5 curtas totalmente produzidos com alunos das
  	 	   	    escolas municipais de Alvorada:  A gangue do batom, Quem vê bullying não ve coração,
  	 	   	    O ano do tsunami (Selecionado para 11 Santa Maria Vídeo e Cinema/2013) e traz papel!
  	 	   	    (Vencedor do 7 festival Cine Favela-SP).

  	 	   		  No momento Evandro está em fase de pré produção do seu 4 longa metragem, seguindo a sua
  	 	   		  "Trilogia do Ódio" com Eu odeio o Big Bróther, e publicando seu terceiro livro Game Over
  	 	   	    - um inferno chamado casamento, (Besouro Box), lançamento previsto para Junho/2013.</p>
  	 	   	 </div>
  	 	   </div>

  	 	</div><!-- col-md-12 -->
  	 </div><!-- row -->
  </div><!-- container -->
</section>

<section id='projects' ng-controller="ProjectsController as projectCtrl">
   <div class='container'>
   	  <div class='row'>
   	  	<div class='col-md-12'>
   	  		<ul class='list-unstyled text-center'>
   	  		   <li><h1><strong><i class='glyphicon glyphicon-search'></i>
             PROJETOS</h1></strong></li>
   	  		   <li><p>Conheça nossos projetos.</p></li>
   	  		   <li><br></li>
   	  		</ul><!-- list-unstyled -->

   	  		<div class='col-md-4 col-xs-6 col-sm-6'
           ng-repeat="project in projectCtrl.projects">
   	  		  <div class='project panel panel-default'>
   	  		  	<ul class='list-unstyled padding'>
   	  		  	   <li><a href=''><h4><strong>{{ project.name }}</strong></h4></li></a>
   	  		  	   <li><p>{{ project.description | limitTo : 70 }}</p></li>
   	  		  	   <li><button class='btn btn-primary btn-lg top'>
   	  		  	     VER MAIS
   	  		  	   </button></li>
   	  		  	</ul><!-- list-unstyled -->
   	  		  </div><!-- panel panel-default -->
   	  		</div><!-- col-md-4 -->

   	  	</div><!-- col-md-12 -->
   	  </div><!-- row -->
   </div><!-- container -->
</section><!-- projects -->

<section id='films' ng-controller="FilmsController as filmCtrl">
  <div class='container'>
  	<div class='row'>
  	   <div class='col-md-12'><br><br>
  	   	  <ul class='list-unstyled text-center'>
  	   	  	 <li><h1><strong><i class='glyphicon glyphicon-search'></i> FILMES</h1></strong></li>
  	   	  	 <li><p>Conheça nossos filmes</p></li>
  	   	  </ul><!-- list-unstyled -->

  	   	  <div class='col-md-12'>
  	   	  	<div class='col-md-4 col-md-offset-4'>
  	   	  		<%= form_for(:film) do |f| %>
                <div class='field'>
                  <%= f.text_field :name, class: 'form-control', required: 'required',
                  placeholder: 'Buscar filme...', autocomplete: 'off', 'ng-model': 'name' %>
                </div><!-- field -->
  	   	  		<% end %><br>
  	   	  	</div><!-- col-md-4 -->
  	   	  </div><!-- col-md-12 -->

  	   	  <div class='film col-md-4 col-sm-4 col-xs-6'
            ng-repeat="film in filmCtrl.films | filter: name | limitTo: 3 ">
  	   	  	 <div class='panel panel-default'>
              <div class='thumb'></div>
  	   	  	 	<ul class='list-unstyled text-center padding'>
  	   	  	 		<li><a href=''><h4><strong>{{ film.name }}</strong></h4></a></li>
  	   	  	 		<li><p>{{ film.description | limitTo: 87 }}...</p></li>
                <ul class='list-unstyled list-inline'>
                  <li><button class='btn btn-default btn-lg top'>VER MAIS</button></li>
                  <li><button class='btn btn-default btn-lg top'>COMPARTILHAR</button></li>
                </ul>
              </ul><!-- list-unstyled -->
  	   	  	 </div><!-- panel panel-default -->
  	   	  </div><!-- col-md-4 -->

          <div class='row'>
            <div class="col-md-12" ng-show='filmCtrl.films.length == 0 | filter: name '>
               <p class='well text-center'>
                  Nenhum filme encontrado para <a href=''>{{ name }}</a>
               </p>
            </div><!-- col-md-12 -->
          </div><!-- row <--></-->
  	   </div><!-- col-md-12 -->
  	</div><!-- row -->
  </div><!-- container -->
</section><!-- films -->

<section id='mobile'>
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class='col-md-5'>

        </div><!-- col-md-6 -->

        <div class='col-md-7'>
         <ul class='list-unstyled'>
           <li><h1>ALVOÇORO NO CELULAR</h1></li>
           <li><p>Em breve nosso aplicativo para celular.</p></li>
           <ul class='list-unstyled list-inline' id='app-download'>
              <li><button class='btn btn-primary btn-lg top'>
                <%= fa_icon 'apple' %> APPLE STORE</button></li>
              <li><button class='btn btn-primary btn-lg top'>
                <%= fa_icon 'android' %> APP STORE</button></li>
              <li><button class='btn btn-primary btn-lg top'>
                <%= fa_icon 'windows' %> WIN STORE
              </button></li>
           </ul><!-- list-unstyled -->
         </ul><!-- list-unstyled -->
       </div><!-- col-md-6 -->

      </div><!-- col-md-12 -->
    </div><!-- row -->
  </div><!-- container -->
</section><!-- mobile -->

<section id='contact'>
	<div class='container'>
	   <div class='row'>
	   	  <div class='col-md-12'>
	   	  	 <ul class='list-unstyled text-center'>
	   	  	 	<li><h1><i class='glyphicon glyphicon-search'></i> CONTATO</h1></li>
	   	  	 	<li><p>Entre em contato conosco.<p></li>
	   	  	 	<li><br></li>
	   	  	 </ul><!-- lsit-unstyled -->

	   	  	 <div class='col-md-12'>
	   	  	   <%= render partial: 'contact/form' %>
	   	   	 </div>
	   	  </div><!-- col-md-12 -->
	   </div><!-- row -->
	</div><!-- container -->
</section><!-- contact -->

<%= render partial: 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
  	 <div class="row">
  	 	 <div class="col-md-12">
           <div class="col-md-4 col-sm-4 col-xs-4">
             <ul class='list-unstyled'>
                <li><%= image_tag('', class: 'logo') %></li>
                <li><h5>Engeneering by <a href='http://code7even.com'
                target='_blank'><b>CODE7EVEN</b></a></p></li>
                <li><small>SOFTWARE <a>DEVELOPMENT</a> AND <a>CONSULTANCE</a>.</p></li>
             </ul>
           </div>
           <div class="col-md-4 col-sm-4 col-xs-4" id='midia'>
             <ul class='list-unstyled list-inline text-center'>
              <li><a href="#"><%= fa_icon 'twitter' %></a></li>
              <li><a href="#"><%= fa_icon 'facebook' %></a></li>
              <li><a href="#"><%= fa_icon 'linkedin' %></a></li>
            </ul>
           </div>
           <div class="col-md-4 col-sm-4 col-xs-4">
             <ul class='list-unstyled'>
               <li><h4><strong><i class='glyphicon glyphicon-search'></i> EXTRAS</strong></h4></li>
               <ul class='list-unstyled list-inline'>
                  <li><%= link_to 'POLITICA DE PRIVACIDADE', '' %></li>
                  <li><%= link_to 'TERMOS DE USO', '' %></li>
                  <li><%= link_to 'COOKIES', '' %></li>
               </ul><!-- list-unstyled -->
               <li><h5>COPYRIGHT &copy <strong>ALVOROÇO
               FILMES</strong> <%= Date.today.year %></h5></li>
             </ul><!-- list-unstyled -->
           </div>

           <div class="col-md-12 col-sm-12 col-xs-12">
             <ul class='list-unstyled text-center'>
                <li><h4><strong><i
                class='glyphicon glyphicon-search'></i> SITEMAP</strong></h4></li>
                <ul class='list-unstyled list-inline'>
                   <li><%= link_to 'HOME',     '#home'     %></li>
                   <li><%= link_to 'SOBRE',    '#about'    %></li>
                   <li><%= link_to 'PROJETOS', '#projects' %></li>
                   <li><%= link_to 'FILMES',   '#films'    %></li>
                   <li><%= link_to 'CONTATO',  '#contact'  %></li>
                </ul>
             </ul><!-- list-unstyled
           </div><!-- col-md-12 -->

  	 	 </div><!-- col-md-12 -->
  	 </div><!-- row -->
  </div><!-- container -->
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'ALVOROÇO FILMES', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">

        <ul class="nav navbar-nav">
           <li class='active'><%= link_to 'Home',     '#home'     %></li>
           <li><%= link_to 'Sobre',    '#about'    %></li>
           <li><%= link_to 'Projetos', '#projects' %></li>
           <li><%= link_to 'Filmes',   '#films'    %></li>
           <li><%= link_to 'Contato',  '#contact'  %></li>
        </ul><!-- list-unstyled -->

        <ul class="nav navbar-nav navbar-right">
           <li><a href="#"></a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<htm ng-app='app'>
  <head>
    <title> Alvoroco Filmes | <%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<style><%= yield :css %></style>
  	<javascript><%= yield :js %></javascript>
  </head>

  <body class="<%= controller.controller_name %>" 
  	ng-controller='ApplicationController' data-spy='scroll'>
    <%= yield %>
  </body>
</html>